version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./csv:/var/lib/postgresql/csv
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the seed data script

  gateway:
    build:
      context: ../..
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    command:
      - start
      - --config
      - /usr/local/bin/config.yaml
      - --addr
      - ":8182"
      - rest
    depends_on:
      - postgres
    ports:
      - "8182:8182"
    volumes:
      - ./config.yaml:/usr/local/bin/config.yaml

volumes:
  postgres_data:
