name: Release Docker Branch

on:
  push:
    branches: [ '*' ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: ./.github/workflows/build-docker.yml
    with:
      version: ${{ github.ref_name }}

