name: Release Docker Latest

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  release:
    uses: ./.github/workflows/build-docker.yml
    with:
      version: latest

